parameters:
    ezifttt.content_provider.demo.class: BD\Bundle\EzIFTTTDemoBundle\ContentProvider\Demo

services:
    ezifttt.content_provider.demo:
        base: ezifttt.content_provider.simple
        class: %ezifttt.content_provider.demo.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.location
        calls:
            - [ setUserService, [ @ezpublish.api.service.user] ]

    ezifttt.content_provider:
        alias: ezifttt.content_provider.demo
